name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      -  name: Install Corepack
         # See: [actions/setup-node/issues/1222](https://github.com/actions/setup-node/issues/1222)
         run: |
           npm i -g --force corepack
         shell: bash

      - name: Enable Corepack
        run: |
          corepack enable
          pnpm -v
        shell: bash

      - name: Install dependencies
        run: pnpm i

      - name: Run linters
        run: pnpm lint

      - name: Run unit test
        run: pnpm test

      - name: Build the app
        run: pnpm build
