on:
  push:
    branches:
      - main
name: release-please
permissions: {}
jobs:
  release-please:
    permissions:
      contents: write # to create release commit (google-github-actions/release-please-action)
      pull-requests: write # to create release PR (google-github-actions/release-please-action)

    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
          package-name: composerize-ts
          bump-minor-pre-major: true

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - run: corepack enable
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          always-auth: true
          cache: 'pnpm'
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: pnpm i
        if: ${{ steps.release.outputs.release_created }}

      - name: Run linters
        run: pnpm lint
        if: ${{ steps.release.outputs.release_created }}

      - name: push release
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
